// TECH USERS
export const GET_TECH_USERS_ALL = "GET_TECH_USERS_ALL";
export const GET_TECH_USERS_BY_ID = "GET_TECH_USERS_BY_ID"
export const GET_TECH_USERS_BY_JOB_ZONE= "GET_TECH_USERS_BY_JOB_ZONE"

